hmmlearn/hmm.py

Multinomial emission probabilities should be normalised per state.

Fix multinomial emission probabilities

---

hmmlearn/base.py

Add two extra attributes: n_iterations_performed and logprob_delta to allow users to gain insight into the convergence behaviour

Add requested attribute from issue #1

---

doc/tutorial.rst

Hi!
There seems to be a typo in documentation.

DOC incorrect startprob_ in left-right HMM example

---

doc/index.rst

Just one mini typo on doc homepage

---

examples/plot_hmm_stock_analysis.py

The plot was not showing up for me (and a friend of mine on a Windows machine). plt.show() helped.

fixes plot not displaying

---

.gitignore
hmmlearn/hmm.py

This *greatly* accelerates fitting of models with a tied or full covariance matrix.

Vectorize statistics accumulation

---

hmmlearn/hmm.py

BUG fixed TypeError during the test.

---

hmmlearn/base.py
hmmlearn/utils.py

Handle ZERO start/transition probabilities.

---

doc/GMMHMM.rst
hmmlearn/hmm.py
hmmlearn/tests/test_gmm_hmm_new.py

I rewrote GMMHMM from the ground up without the use of GMM from scikit-learn. It is still work in progress, and I haven't yet wrote any tests for it.

Completely rewrite GMMHMM

---

hmmlearn/hmm.py

Fix #297: check random state in _generate_sample_from_state

---

hmmlearn/tests/__init__.py
hmmlearn/tests/test_gaussian_hmm.py

Extracted from #241, thanks @stevenjkern.

FIX: pass RandomState to make make_covar_matrix reproducible

---

CHANGES.rst
lib/hmmlearn/hmm.py
lib/hmmlearn/tests/test_multinomial_hmm.py

Allow unsigned symbols in MultinomialHMM.

---

README.rst

Mention that a C compiler is (currently) required for install.

---

CHANGES.rst
lib/hmmlearn/base.py
lib/hmmlearn/tests/test_base.py

Add `model.get_stationary_distribution()`.

---

.gitignore
doc/source/tutorial.rst

Fix incorrect description of likelihood, which is either the likelihood of the *model* (given the data) or the probability of the data (given the model)

Mod 1/3 fundamental problem summaries

---

lib/hmmlearn/hmm.py

This provides a a significant performance improvement - ~3x for the scaling implementation, 2x for the Logarithm implementation.

Use numpy array operations to accumulate Multinomial emissions statistics`

---

lib/hmmlearn/_hmmc.pyx
lib/hmmlearn/base.py

I think this is a nicer API to work with (afaict there isn't any advantage in preallocating the arrays from outside cython rather than inside).  @blckmaxima any thoughts on this?

Switch cython APIs to return new arrays.

---

lib/hmmlearn/tests/test_gaussian_hmm.py
lib/hmmlearn/utils.py

Test spherical covar GaussianHMM where n_features is not set correctly

---

lib/hmmlearn/hmm.py

[MAINT, MRG] Add uniform prior to Poisson

---

CHANGES.rst
doc/source/tutorial.rst
examples/plot_hmm_sampling_and_decoding.py
lib/hmmlearn/base.py
lib/hmmlearn/tests/test_gaussian_hmm.py
lib/hmmlearn/tests/test_gmm_hmm_multisequence.py
lib/hmmlearn/tests/test_gmm_hmm_new.py

Fixes https://github.com/hmmlearn/hmmlearn/issues/419

[ENH, MRG] Add Dirichlet random initialization of priors on startprob and transmat

---

doc/source/api.rst
doc/source/tutorial.rst
examples/plot_variational_inference.py
lib/hmmlearn/_emissions.py
lib/hmmlearn/_kl_divergence.py
lib/hmmlearn/base.py
lib/hmmlearn/hmm.py
lib/hmmlearn/tests/__init__.py
lib/hmmlearn/tests/test_base.py
lib/hmmlearn/tests/test_categorical_hmm.py
lib/hmmlearn/tests/test_gaussian_hmm.py
lib/hmmlearn/tests/test_gmm_hmm_new.py
lib/hmmlearn/tests/test_kl_divergence.py
lib/hmmlearn/tests/test_multinomial_hmm.py
lib/hmmlearn/tests/test_poisson_hmm.py
lib/hmmlearn/tests/test_variational_categorical.py
lib/hmmlearn/tests/test_variational_gaussian.py
lib/hmmlearn/vhmm.py

@anntzer  Leaving an early draft of incorporating Variational Inference training of HMMs so I may receive feedback before I keep going.
Some Notes:
* I derive from BaseHMM, and am able to reuse most of it, with a few exceptions.
* `VariationalGaussianHMM` is still incomplete - only Full Covariance is supported.
* Tests are lacking.
Up Next:
* Finish the different covariance types for Gaussian
* Add Mixture of Gaussian Emissions

Variational inference

---

lib/hmmlearn/tests/test_variational_gaussian.py
lib/hmmlearn/vhmm.py

Round out tests for Guassian vhmm

Finish the Gaussian vhmm

---

examples/plot_gaussian_model_selection.py
lib/hmmlearn/base.py
lib/hmmlearn/hmm.py
lib/hmmlearn/tests/test_gaussian_hmm.py
lib/hmmlearn/tests/test_gmm_hmm_new.py
lib/hmmlearn/tests/test_poisson_hmm.py

Expand the work done in the other MR to make AIC / BIC available for Gaussian, GMM, and Poisson HMMs. 
Q - are these also available for other models?  In one reference I see an assumption of Gaussian-like models, However in the Zucchini, MacDonald, and Langrock book they also apply it to Poisson models...

Criterion - AIC / BIC

---

examples/plot_gaussian_model_selection.py

@anntzer is there a way to see the produced html docs before merging? I poked around the ci/cd a bit, but it was not immediately obvious.  I'm attempting to make the example output reproducible and show a clear minimum for the aic/bic at 4 states.

Correct the model-selection example

---

doc/source/tutorial.rst
lib/hmmlearn/base.py
lib/hmmlearn/tests/test_variational_gaussian.py
lib/hmmlearn/vhmm.py

Addressing subtle issues with the Variational Gaussian HMM

Fix gaussian vhmm

---

lib/hmmlearn/base.py
lib/hmmlearn/hmm.py
lib/hmmlearn/vhmm.py

- Fixes #532 
This is an attempt to clarify the difference between "viterbi" and "map" decoding. I hope my explanations are correct and understandable.

Improve documentation of the `algorithm` parameter

---

ext/_hmmc.cpp

... as explicitly required by pybind11.  Compile with `#define PYBIND11_ASSERT_GIL_HELD_INCREF_DECREF` to observe GIL assertion failures in absence of this patch.
Closes (and supersedes) #564.
(See item regarding "pybind11 objects that are members of other C++ structures" in https://pybind11.readthedocs.io/en/stable/advanced/misc.html#common-sources-of-global-interpreter-lock-errors)

Reacquire GIL before constructing tuples containing numpy arrays.
